name: otter-grader
channels: 
    - conda-forge
    - defaults
dependencies:
    - python>=3.9
    - liblzma-devel
    - zlib-devel-amzn2-aarch64
    - zlib
    - r-base>=4.0.0
    - r-essentials
    - r-devtools
    - pip
    - nb_conda_kernels
    - jupyter_server
