name: otter-grader
channels: 
    - conda-forge
    - defaults
dependencies:
    - python>=3.6
    - r-base>=4.0.0
    - r-essentials
    - r-devtools
    - pip
    - pip:
        - .
        - .[export]
        - .[test]
        - -r docs/requirements.txt
