name: otter-grader
channels: 
    - conda-forge
    - defaults
dependencies:
    - python>=3.6
    - pip
    - pip:
        - .
        - -r docs/requirements.txt
        - nbconvert
        - ipython
