# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: before install
        run: |
          docker version
          docker-compose version
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          hash -r
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
          source activate test-env
          export TAR="/bin/tar"
          docker pull gradescope/auto-builds:latest
          
      - name: install
        run: |
          conda install r-base r-essentials
          conda install r-devtools -c conda-forge
          pip install -r requirements.txt
          Rscript -e "devtools::install_github('ucbds-infra/ottr')" || Rscript -e "devtools::install_github('ucbds-infra/ottr')"
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-generic-recommended texlive-generic-extra
          sudo apt-get install fonts-lmodern
          make docker-test
          
      - name: before script
        run: |
          docker version
          docker-compose version
          conda info -a
          psql -c "create user root createdb password 'root';" -U postgres
          
      - name: script
        run: coverage run -m test
      
      - name: after success
        run: codecov
