# Workflow for running the test suite

name: Run tests

on:
  push:
    branches:
      - master
      - beta
      - release
  pull_request:
    branches:
      - master
      - beta
      - release
      - temp
  workflow_dispatch:

jobs:
  build:
    name: Test suite
    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: liskin/gh-pipx@v1
        with:
          packages: >-
            poetry

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          cache-environment-key: requirements-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          micromamba activate otter-grader
          poetry install --with dev,test --all-extras

      - name: Install ottr
        run: |
          micromamba run -n otter-grader Rscript -e 'install.packages("ottr", dependencies=TRUE, repos="https://cran.r-project.org/")'

      - name: Run tests
        run: |
          micromamba activate otter-grader
          make testcov DOCKER=false PYTESTOPTS="-vv" && coverage lcov -i

      - name: Coveralls
        uses: coverallsapp/github-action@v2
